version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: uv
    directory: "/python"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "/ts"
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: "/go"
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: "/conformance/matrix/cli_go"
    schedule:
      interval: monthly
